version: "3.3"
services:
    mynginx:
        image: nginx:latest
        container_name: mynginx
        ports:
          - "8080:80"
        restart: always
        privileged: true
        volumes:
          - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
          - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
          - ./src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
          - ./src/:/var/www/html
        networks:
          - app-network

    myredis-master:
        image: 'bitnami/redis:latest'
        restart: always
        user: root
        ports:
          - '6379'
        environment:
          - REDIS_REPLICATION_MODE=master
          - REDIS_PASSWORD=my_master_password
        volumes:
          - './radis:/bitnami'
        networks:
          - app-network

    myredis-replica:
        image: 'bitnami/redis:latest'
        user: root
        restart: always
        ports:
          - '6379'
        depends_on:
          - myredis-master
        environment:
          - REDIS_REPLICATION_MODE=slave
          - REDIS_MASTER_HOST=myredis-master
          - REDIS_MASTER_PORT_NUMBER=6379
          - REDIS_MASTER_PASSWORD=my_master_password
          - REDIS_PASSWORD=my_replica_password
        networks:
          - app-network
    
    myphp:
        build: ./src/php
        ports:
          - "9000"
        restart: always
        volumes:
          - ./src/:/var/www/html
        depends_on:
          - mysql
          - myredis-master
          - myredis-replica
        networks:
          - app-network
    
    mysql:
        image: mysql:latest
        container_name: dev_mysql
        environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: default_schema
        volumes:
           - my-datavolume:/var/lib/mysql
        ports:
           - "3306:3306"
        networks:
          - app-network
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dev_pma
        links:
          - mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        restart: always
        networks:
          - app-network
        ports:
          - 9090:80

networks:
    app-network:
        driver: bridge
volumes:
     my-datavolume:
